name: CI - Build, Test, and Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend (Node.js/Svelte)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

  backend:
    name: Backend (Go/Gin)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: 'backend/go.sum'
        
    - name: Install dependencies
      working-directory: ./backend
      run: go mod download
      
    - name: Run linting (go vet)
      working-directory: ./backend
      run: go vet ./...
      
    - name: Build backend
      working-directory: ./backend
      run: go build ./...
      
    - name: Run tests
      working-directory: ./backend
      run: go test ./...